django_test/src/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [ 
    path('books_view/', views.BooksList.as_view(), name = "book-view-all"),
    path('book_view/<int:pk>/', views.BookView.as_view(), name = "book-view"),
    path('book_add/', views.BookAdd.as_view(), name = "book-add"),
    path('book_delete/<int:pk>/', views.BookDelete.as_view(), name = "book-delete"),
    path('book_edit/<int:pk>/', views.BookEdit.as_view(), name = "book-edit"),

]

django_test/src/directory/urls.py
from django.urls import path
from . import views

app_name = 'dirs'

urlpatterns = [ 
    path('', views.Homepage.as_view(), name = "home-page"),

    # path('books_view/', views.BooksList.as_view(), name = "book-view-all"),
    # path('book_view/<int:pk>/', views.BookView.as_view(), name = "book-view"),
    # path('book_add/', views.BookAdd.as_view(), name = "book-add"),
    # path('book_delete/<int:pk>/', views.BookDelete.as_view(), name = "book-delete"),
    # path('book_edit/<int:pk>/', views.BookEdit.as_view(), name = "book-edit"),
    
    path('authors_view/', views.AuthorsList.as_view(), name = "author-view-all"),
    path('author_view/<int:pk>/', views.AuthorView.as_view(), name = "author-view"),
    path('author_edit/<int:pk>/', views.AuthorEdit.as_view(), name = "author-edit"),
    path('author_delete/<int:pk>/', views.AuthorDelete.as_view(), name = "author-delete"),
    path('author_add/', views.AuthorAdd.as_view(), name = "author-add"),

    path('publishings_view/', views.PublishingsList.as_view(), name = "publishing-view-all"),
    path('publishing_view/<int:pk>/', views.PublishingView.as_view(), name = "publishing-view"),
    path('publishing_edit/<int:pk>/', views.PublishingEdit.as_view(), name = "publishing-edit"),
    path('publishing_delete/<int:pk>/', views.PublishingDelete.as_view(), name = "publishing-delete"),
    path('publishing_add/', views.PublishingAdd.as_view(), name = "publishing-add"),

    path('serieses_view/', views.SeriesList.as_view(), name = "series-view-all"),
    path('series_view/<int:pk>/', views.SeriesView.as_view(), name = "series-view"),
    path('series_edit/<int:pk>/', views.SeriesEdit.as_view(), name = "series-edit"),
    path('series_delete/<int:pk>/', views.SeriesDelete.as_view(), name = "series-delete"),
    path('series_add/', views.SeriesAdd.as_view(), name = "series-add"),

    path('genres_view/', views.GenresList.as_view(), name = "genres-view-all"),
    path('genre_view/<int:pk>/', views.GenreView.as_view(), name = "genre-view"),
    path('genre_edit/<int:pk>/', views.GenreEdit.as_view(), name = "genre-edit"),
    path('genre_delete/<int:pk>/', views.GenreDelete.as_view(), name = "genre-delete"),
    path('genre_add/', views.GenreAdd.as_view(), name = "genre-add"),

]

django_test/src/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [ 
    path('add-to-cart', views.AddToCart.as_view(), name = "add-to-cart"),
    path('books_list', views.BooksInCartList.as_view(), name = "books_list"),
    path('delete_from_cart/<int:pk>', views.DeleteFromCart.as_view(), name = "delete_from_cart"),
    path('update-carts', views.OrderUpdateView.as_view(), name = "update-carts"),
    path('order-confirm', views.OrderConfirm.as_view(), name = "order-confirm"),
    path('order-status', views.OrderStatus.as_view(), name = "order-status"),
    path('order-status-update', views.ChangeStatus.as_view(), name = "order-status-update"),


]

django_test/src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from directory import views as dir
from django.conf import settings
from django.conf.urls.static import static
from . import local_vars 

urlpatterns = [ 
    path('', dir.Homepage.as_view(), name = "home-page"),
    path('admin/', admin.site.urls, name = "admin"),

    path("dirs/", include('directory.urls', namespace='dirs')),
    path("books/", include('books.urls', namespace='books')),
    path("sales/", include('sales.urls', namespace='sales')),
    path("auth/", include('auth_user.urls', namespace='auth_user')),
    path("orders/", include('orders.urls', namespace='orders')),
    path("managers/", include('manager_page.urls', namespace='managers')),
    
] 

if local_vars.SERVER == 'local':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_test/src/books/models.py
from statistics import quantiles
from django.db import models

# Create your models here.

class Book(models.Model):
    genre = models.ManyToManyField(
        'directory.Genre',
        verbose_name='Genre',
        related_name='genres'
    )
    publishing = models.ForeignKey(
        'directory.Publishing_house',
        on_delete=models.PROTECT,
        verbose_name='Publishing',
        related_name='publishing'
    )
    author = models.ManyToManyField(
        'directory.Author',
        verbose_name='Author',
        related_name='author'
    )
    name = models.CharField(
        verbose_name='Book name',
        max_length=30,
    )

    series = models.CharField(
        verbose_name='Book series',
        max_length=30,
        blank =  True,
        null = True
    )

    description= models.TextField(
        verbose_name='Book description',
        blank =  True,
        null = True
    )

    picture = models.ImageField(
        verbose_name='Sales picture',
        upload_to = 'uploads/%Y/%m/%d/',
        blank =  True,
        null = True
    )

    quantity = models.SmallIntegerField(
        verbose_name= "Quantity",
    )

    price = models.DecimalField(
        verbose_name= "Price",
        decimal_places=2,
        max_digits=7,
        default=5
    )

    def __str__(self) -> str:
        return str(self.pk) + '. ' + self.name

django_test/src/books/forms.py
from django import forms
from . import models

class AddBookForm(forms.ModelForm):
    class Meta:
        model = models.Book
        fields = '__all__'

django_test/src/books/views.py
from books import models
from directory import models as dirs_model
from . import forms
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from orders import models as order_model
# Create your views here.

#  Books
class BooksList(generic.ListView):
    template_name = "books/books_view.html"
    model = models.Book

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        try:
            cart = order_model.Cart.objects.get(customer = self.request.user)
            context['session'] = cart.session_id
        except:
            True
        return context
    

class BookView(generic.DetailView):
    template_name = "books/book_view.html"
    model = models.Book
 
    def get_context_data(self,*args, **kwargs):

        context = super().get_context_data(*args, **kwargs)
        authors = self.object.author.all()
        genres = self.object.genre.all()
        publishings = self.object.publishing

        series = self.object.series
        if series:
            series_m = dirs_model.Series.objects.get(name = series )
        else:
            series_m = ""
        context['authors'] = authors
        context['genres'] = genres
        context['publishings'] = publishings
        context['series'] = series_m
        return context

class BookAdd(PermissionRequiredMixin,generic.CreateView):
    template_name = "books/book_add.html"
    model = models.Book
    form_class = forms.AddBookForm
    permission_required = 'books.add_book'

    
    def get_success_url(self):
        return reverse_lazy("books:book-view", kwargs = {'pk' : self.object.pk})

class BookEdit(PermissionRequiredMixin,generic.UpdateView):
    template_name = "books/book_edit.html"
    model = models.Book
    form_class = forms.AddBookForm
    permission_required = 'books.change_book'

    def get_success_url(self):
        return reverse_lazy("books:book-view", kwargs = {'pk' : self.object.pk})

class BookDelete(PermissionRequiredMixin,generic.DeleteView):
    template_name = "books/book_delete.html"
    model = models.Book
    success_url = "/books/books_view/"
    permission_required = 'books.delete_book'

django_test/src/books/templates/books/book_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Books add{% endblock title %}

{% block header %}Books add{% endblock header %}

{% block body %}
    <ul>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-primary">
        </form>
    </ul>

{% endblock body %}

django_test/src/books/templates/books/book_delete.html
{% extends 'base.html' %}

{% block title %}Books view{% endblock title %}

{% block header %}Book delete. Are you sure to delete {{ object.name }} ??{% endblock header %}

{% block body %}
        <form action="" method="post">
            {% csrf_token %}
            <br>
            <input type="submit">
        </form>
{% endblock body %}

django_test/src/books/templates/books/book_edit.html
{% extends 'base.html' %}

{% block title %}Books edit{% endblock title %}

{% block header %}Books edit{% endblock header %}

{% block body %}
    <ul>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </ul>



    
{% endblock body %}

django_test/src/books/templates/books/book_view.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Book {{ object.name }}{% endblock title %}

{% block header %}Book {{ object.name }} information{% endblock header %}

{% block body %}

    {% if authors %}
        <b>Author:</b> <br>
        {% for author in authors %}
            <a href="{% url 'dirs:author-view' author.pk %}">{{ author.name }}</a><br>
        {% endfor%}
    {% else%}
        <p>There is no such information yet</p>
    {% endif %}

    {% if publishings %}
        <b>Publishing:</b> <br>
        <a href="{% url 'dirs:publishing-view' publishings.pk %}">{{ publishings.name }}</a><br>
    {% else%}
        <p>There is no such information yet</p>
    {% endif %}

    {% if series %}
        <b>Series:</b><br>
        <a href="{% url 'dirs:series-view' series.pk %}">{{ series.name }}</a><br>
    {% else%}
        <b>Series:</b><br>
        <p>There is no such information yet</p>
    {% endif %}

    {% if genres %}
        <b>Genre:</b> <br>
        {% for genre in genres %}
        <a href="{% url 'dirs:genre-view' genre.pk %}">{{ genre.name }}</a><br>
        {% endfor%}
    {% else%}
        <p>There is no such information yet</p>
    {% endif %}
    <br>

    {% if object.description %}
        <b>Description:</b> {{ object.description }}<br><br>
    {% else%}
        <b>Description:</b><br>
        <p>There is no such information yet</p>
    {% endif %}

    <b>Price:</b> {{ object.price }} USD<br><br>

    {% if object.picture %}
    <img src="{{ object.picture.url }}" alt="..." width=150px height=200px>
    {% else %}
    <img src="{% static 'images.jfif' %}" alt="..."width=150px height=200px>
    {% endif %}
    
    <br><br><br>
    <form action="{% url 'orders:add-to-cart' %}" method="post">
        {% csrf_token %}
            <div style="display:inline">
                <button type="submit" class="btn btn-primary">
                    <a href=""></a><i class="bi bi-cart4"></i></i></a>
                </button>
            </div>
            <div style="display:inline">
                <input type="hidden" name="book_id" value="{{ object.pk }}">
                {% if user.is_authenticated %}
                    <input type="number" name="quantity" min = "1" max = "{{ object.quantity }}" step="1" value="1" style="width: 60px;">
                {% else %}
                    <input type="number" name="quantity" min = "1" max = "1" step="1" value="1" style="width: 60px;">
                {% endif %}
            </div>
    </form>


    <br><br>
    <a href="{% url 'books:book-view-all' %}"><button type="button" class="btn btn-primary">All Books</button></a>
    
    <br><br><br>

    {% for group in request.user.groups.all %}
    {% if group.name == 'Admin' or group.name == 'Super_managers' %}
        <a href="{% url 'books:book-edit' object.pk %}" class="btn btn-primary"><i class="bi bi-pencil"></i></a>
        <a href="{% url 'books:book-delete' object.pk %}" class="btn btn-primary"><i class="bi bi-trash"></i></a>
    {% elif group.name == 'Managers'%}
        <a href="{% url 'books:book-edit' object.pk %}" class="btn btn-primary"><i class="bi bi-pencil"></i></a>
    {% elif group.name == 'Users'%}
    <button type="button" class="btn btn-primary"><a href="#"></a><i class="bi bi-cart4"></i></i></a></button>
    {% endif %}
    {% endfor %}

{% endblock body %}

django_test/src/books/templates/books/books_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Books view{% endblock title %}

{% block header %}Books view{% endblock header %}

{% block body %}

    <div class="container">
        <div class="row">
            {% for obj in object_list %}
                <div class="col-xxl-3 col-xl-4 col-lg-4 col-md-5">
                <div class="card" style="width: 300px; height: 550px; float: left; padding: 10px; margin: 10px;">
                    {% if obj.picture %}
                        <img src="{{ obj.picture.url }}" class="card-img-top" alt="..." width=308px height=250px>
                    {% else %}
                        <img src="{% static 'images.jfif' %}" class="card-img-top" alt="..."width=308px height=250px>
                    {% endif %}
                    
                    <div class="card-body">
                        <h5 class="card-title">{{ obj.name }}</h5>
                        <p class="card-text" style="text-overflow: ellipsis; overflow: hidden; -webkit-line-clamp: 4; white-space: nowrap;">{{ obj.description }}</p>
                        <p class="card-text">Price for 1 piece: {{ obj.price }} USD</p>  <br>
                        <div style="">
                            <a href="{% url 'books:book-view' obj.pk %}" class="btn btn-primary">View</a>
                        
                            {% for group in request.user.groups.all %}
                            {% if group.name == 'Admin' or group.name == 'Super_managers' %}
                                <a href="{% url 'books:book-edit' obj.pk %}" class="btn btn-primary"><i class="bi bi-pencil"></i></a>
                                <a href="{% url 'books:book-delete' obj.pk %}" class="btn btn-primary"><i class="bi bi-trash"></i></a>
                            {% elif group.name == 'Managers'%}
                                <a href="{% url 'books:book-edit' obj.pk %}" class="btn btn-primary"><i class="bi bi-pencil"></i></a>
                            {% endif %}
                            {% endfor %}
                            <br><br>
                            <form action="{% url 'orders:add-to-cart' %}" method="post">
                                {% csrf_token %}
                                <div class="form-group row">
                                    <div class="col-3">
                                        <button type="submit" class="btn btn-primary">
                                            <a href=""></a><i class="bi bi-cart4"></i></i></a>
                                        </button>
                                    </div>
                                    <div class="col-1">
                                        <input type="hidden" name="book_id" value="{{ obj.pk }}">
                                        {% if user.is_authenticated %}
                                            <input type="number" name="quantity" min = "1" max = "{{ obj.quantity }}" step="1" value="1" style="width: 60px;">
                                        {% else %}
                                            <input type="number" name="quantity" min = "1" max = "1" step="1" value="1" style="width: 60px;">
                                        {% endif %}
                                    </div>
                                </div>
                            </form>
                            
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div> 
    </div>

    <br><br>
    {% for group in request.user.groups.all %}
    {% if group.name == 'Admin' or group.name == 'Super_managers' or group.name == 'Managers' %}
        <a href="{% url 'books:book-add' %}"><button type="button" class="btn btn-primary">Add Book</button></a>
    {% endif %}
    {% endfor %}
<br>

{% endblock body %}