django_test/src/auth_user/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [ 
    path('login', views.LoginUserView.as_view(), name = "login"),
    path('logout', views.LogoutUserView.as_view(), name = "logout"),
    path('registration', views.register_page, name = "registration"),
    path('user-page', views.UserPage.as_view(), name = "user-page"),
    path('settings', views.UserSettings.as_view(), name = "settings"),
    path('settings-update', views.UserSettingsUpdate.as_view(), name = "settings-update"),
    path('carts-view/', views.CartsList.as_view(), name = "carts-view"),
    path('cart_view/<int:pk>/', views.CartView.as_view(), name = "cart-view"),
    path('cart_view_update/<int:pk>/', views.UpdateCartView.as_view(), name = "cart-view-update"),

]

django_test/src/directory/urls.py
from django.urls import path
from . import views

app_name = 'dirs'

urlpatterns = [ 
    path('', views.Homepage.as_view(), name = "home-page"),

    # path('books_view/', views.BooksList.as_view(), name = "book-view-all"),
    # path('book_view/<int:pk>/', views.BookView.as_view(), name = "book-view"),
    # path('book_add/', views.BookAdd.as_view(), name = "book-add"),
    # path('book_delete/<int:pk>/', views.BookDelete.as_view(), name = "book-delete"),
    # path('book_edit/<int:pk>/', views.BookEdit.as_view(), name = "book-edit"),
    
    path('authors_view/', views.AuthorsList.as_view(), name = "author-view-all"),
    path('author_view/<int:pk>/', views.AuthorView.as_view(), name = "author-view"),
    path('author_edit/<int:pk>/', views.AuthorEdit.as_view(), name = "author-edit"),
    path('author_delete/<int:pk>/', views.AuthorDelete.as_view(), name = "author-delete"),
    path('author_add/', views.AuthorAdd.as_view(), name = "author-add"),

    path('publishings_view/', views.PublishingsList.as_view(), name = "publishing-view-all"),
    path('publishing_view/<int:pk>/', views.PublishingView.as_view(), name = "publishing-view"),
    path('publishing_edit/<int:pk>/', views.PublishingEdit.as_view(), name = "publishing-edit"),
    path('publishing_delete/<int:pk>/', views.PublishingDelete.as_view(), name = "publishing-delete"),
    path('publishing_add/', views.PublishingAdd.as_view(), name = "publishing-add"),

    path('serieses_view/', views.SeriesList.as_view(), name = "series-view-all"),
    path('series_view/<int:pk>/', views.SeriesView.as_view(), name = "series-view"),
    path('series_edit/<int:pk>/', views.SeriesEdit.as_view(), name = "series-edit"),
    path('series_delete/<int:pk>/', views.SeriesDelete.as_view(), name = "series-delete"),
    path('series_add/', views.SeriesAdd.as_view(), name = "series-add"),

    path('genres_view/', views.GenresList.as_view(), name = "genres-view-all"),
    path('genre_view/<int:pk>/', views.GenreView.as_view(), name = "genre-view"),
    path('genre_edit/<int:pk>/', views.GenreEdit.as_view(), name = "genre-edit"),
    path('genre_delete/<int:pk>/', views.GenreDelete.as_view(), name = "genre-delete"),
    path('genre_add/', views.GenreAdd.as_view(), name = "genre-add"),

]

django_test/src/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [ 
    path('add-to-cart', views.AddToCart.as_view(), name = "add-to-cart"),
    path('books_list', views.BooksInCartList.as_view(), name = "books_list"),
    path('delete_from_cart/<int:pk>', views.DeleteFromCart.as_view(), name = "delete_from_cart"),
    path('update-carts', views.OrderUpdateView.as_view(), name = "update-carts"),
    path('order-confirm', views.OrderConfirm.as_view(), name = "order-confirm"),
    path('order-status', views.OrderStatus.as_view(), name = "order-status"),
    path('order-status-update', views.ChangeStatus.as_view(), name = "order-status-update"),


]

django_test/src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from directory import views as dir
from django.conf import settings
from django.conf.urls.static import static
from . import local_vars 

urlpatterns = [ 
    path('', dir.Homepage.as_view(), name = "home-page"),
    path('admin/', admin.site.urls, name = "admin"),

    path("dirs/", include('directory.urls', namespace='dirs')),
    path("books/", include('books.urls', namespace='books')),
    path("sales/", include('sales.urls', namespace='sales')),
    path("auth/", include('auth_user.urls', namespace='auth_user')),
    path("orders/", include('orders.urls', namespace='orders')),
    path("managers/", include('manager_page.urls', namespace='managers')),
    
] 

if local_vars.SERVER == 'local':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_test/src/auth_user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class CustomUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']

django_test/src/auth_user/views.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import Group, User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView,ListView
from django.shortcuts import render, redirect,resolve_url
from django.urls import reverse_lazy

from .forms import CustomUserForm
from orders import models as order_model

# Create your views here.

def def_next_page(value):
    previous = value.request.META.get('HTTP_REFERER')
    find = ['/auth/','/order/','/orders/','/managers/']
    for url in find:
        x = previous.lower().count(url)
        if x:
            break
    if x:
        next_page = "/"
    else:
        next_page = previous
    return next_page

def if_else(value):
    if value:
        return value
    else:
        value = False
        return value

class LoginUserView(auth_views.LoginView):
    template_name = "auth_user/login.html"
    
    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        return context

    def get_default_redirect_url(self):
        url = reverse_lazy("books:book-view-all")              
        return resolve_url(url)

class LogoutUserView(auth_views.LogoutView):
    template_name = "directory/home_page.html"

    def get_next_page(self):
        next_page = def_next_page(self)
        return next_page

def register_page(request):
    if request.method != 'POST':
        form = CustomUserForm()
    else:
        form = CustomUserForm(request.POST)
        if form.is_valid():
            form.save()
            user_name = request.POST.get("username")
            user = User.objects.get(username = user_name)
            my_group = Group.objects.get(name='Users') 
            user.groups.add(my_group)
            return redirect('auth:login')
    context = {'form': form}
    return render(request, 'auth_user/registration.html', context)

class UserPage(LoginRequiredMixin,TemplateView):
    template_name = "auth_user/user_page.html"
    model = order_model.Cart
    login_url = '/auth/login'

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        customer = self.request.user
        carts = order_model.Cart.objects.filter(customer = customer)
        context['carts'] = carts

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(*args, **kwargs)
        return self.render_to_response(context)
    
class UserSettings(LoginRequiredMixin,TemplateView):
    template_name = "auth_user/user_settings.html"
    model = User
    login_url = '/auth/login'

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        form = CustomUserForm
        context['form'] = form
        context['User_name'] = if_else(self.request.user.username)
        context['First_name'] = if_else(self.request.user.first_name)
        context['Last_name'] = if_else(self.request.user.last_name)
        context['Email'] = if_else(self.request.user.email)
        return context

class UserSettingsUpdate(LoginRequiredMixin,TemplateView):
    template_name = "auth_user/user_settings_update.html"
    model = User
    login_url = '/auth/login'

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
       
        user = User.objects.get(username = self.request.user.username)
        user.username = self.request.POST['username']
        user.email = self.request.POST['email']
        user.first_name = self.request.POST['first_name']
        user.last_name = self.request.POST['last_name']
        user.save()

        context['Email'] = if_else(user.email)
        context['User_name'] = if_else(user.username)
        context['First_name'] = if_else(user.first_name)
        context['Last_name'] = if_else(user.last_name)


        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(*args, **kwargs)
        return self.render_to_response(context)

class CartsList(LoginRequiredMixin,ListView):
    template_name = "auth_user/carts_view.html"
    model = order_model.Cart
    login_url = '/auth/login'

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        customer = self.request.user
        if customer != "AnonymousUser":
            carts = order_model.Cart.objects.filter(customer = self.request.user)
            context['carts'] = carts
        else:
            context['carts'] = None
        return context

class CartView(LoginRequiredMixin,TemplateView):
    template_name = "auth_user/cart_view.html"
    model = order_model.Cart
    login_url = '/auth/login'

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # print(self.request.POST)
        session_id = self.request.POST['session']
        cart = order_model.Cart.objects.get(session_id = session_id)
        books = order_model.BookInCart.objects.filter(cart = cart)
        context['cart'] = cart
        context['books'] = books
        context['session'] = session_id
        if cart.notes:
            note = cart.notes.replace('#', ': ')
        else:
            note = "let's start chat? Say something"
        notes_lines = []
        notes_lines = note.split('\n')
        context['notes_lines'] = notes_lines

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(*args, **kwargs)
        return self.render_to_response(context)

class UpdateCartView(LoginRequiredMixin,TemplateView):
    template_name = "auth_user/cart_view_update.html"
    model = order_model.Cart
    login_url = '/auth/login'

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        # print(self.request.POST)
        session_id = self.request.POST['session']
        cart = order_model.Cart.objects.get(session_id = session_id)
        books = order_model.BookInCart.objects.filter(cart = cart)
        context['cart'] = cart
        context['books'] = books
        
        new_note = self.request.POST['notes']
        note = cart.notes
        note += 'user ' + str(self.request.user) + '#' + str(new_note) + '\n'
        cart.notes = note
        cart.save()
        note = cart.notes.replace('#', ': ')
        notes_lines = []
        notes_lines = note.split('\n')
        context['notes_lines'] = notes_lines

        return context

    def post(self, request, *args, **kwargs):
        context = self.get_context_data(*args, **kwargs)
        return self.render_to_response(context)

django_test/src/auth_user/templates/auth_user/cart_view.html
{% extends 'base.html' %}

{% block title %}Cart view{% endblock title %}

{% block header %}Cart {{ user }} {% endblock header %}   
    
{% block body %}   
<h4>Your book in cart:</h4>
{% for book in books %}
{{book.book.name }}<br>
{% endfor %}
<br>
<h4>Your total price:</h4>
{{cart.total_price}} USD<br>

<br>

{% if cart.status == "Start"%}
<h4>You can edit your cart untill you complete your order:</h4>
    <form action="{% url 'orders:books_list' %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Want to edit?">
        <input type="hidden" name="session" value="{{ cart.session_id }}">
        <input type="hidden" name="customer" value="{{ cart.customer }}">
    </form>
    <br><br>

{% else %}
<h4>You can't edit your cart, managers have already started processing it.</h4>
<h5>Status of your order:  {{cart.status }}</h5>
{%endif%}
<br><br>
{% if cart.status != "Close"%}
<form action="{% url 'orders:order-status-update' %}" method="post">
    {% csrf_token %}
        <input type="submit" value="Whant to cancel?" class="btn btn-danger">
        <input type="hidden" name="session" value="{{ cart.session_id }}">   
        <input type="hidden" name="status_" value="Cancel">   
</form>
{%endif%}

<br>
<h4>Chat: </h4>

{% for line in notes_lines%}
{{line}} <br>
{%endfor%}
<br>
 <form action="{% url 'auth:cart-view-update' cart.session_id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="exampleFormControlTextarea1">Customer message:</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="notes"></textarea>
    </div>
    <p><input type="submit" value="Update/Send message" class="btn btn-primary"></p>
    <input type="hidden" name="session" value="{{ session }}">
</form>


{% endblock body %}

django_test/src/auth_user/templates/auth_user/cart_view_update.html
{% extends 'base.html' %}

{% block title %}Cart view{% endblock title %}

{% block header %}Cart {{ user }} {% endblock header %}   
    
{% block body %}   
<h4>Your book in cart:</h4>
{% for book in books %}
{{book.book.name }}<br>
{% endfor %}
<br><br>
{% if cart.status == "Start"%}
<h4>You can edit your cart untill you complete your order:</h4>
    <form action="{% url 'orders:books_list' %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Want to edit?">
        <input type="hidden" name="session" value="{{ cart.session_id }}">
        <input type="hidden" name="customer" value="{{ cart.customer }}">
    </form>
    <br><br>

{% else %}
<h4>You can't edit your cart, managers have already started processing it.</h4>
<h5>Status of your order:  {{cart.status }}</h5>
{%endif%}

<br><br>
{% if cart.status != "Close"%}
<form action="{% url 'orders:order-status-update' %}" method="post">
    {% csrf_token %}
        <input type="submit" value="Whant to cancel?" class="btn btn-danger">
        <input type="hidden" name="session" value="{{ cart.session_id }}">   
        <input type="hidden" name="status_" value="Cancel">   
</form>
{%endif%}

<br>
<h4>Chat: </h4>
    {% for line in notes_lines%}
        {{line}} <br>
    {%endfor%}

<form action="{% url 'auth:cart-view-update' cart.session_id %}" method="post">
    {% csrf_token %}
        <input type="hidden" name="session" value="{{ session }}">
        <div class="form-group">
            <label for="exampleFormControlTextarea1">Customer message:</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="notes"></textarea>
        </div>
        <p><input type="submit" value="Update/Send message" class="btn btn-primary"></p>
</form>



{% endblock body %}

django_test/src/auth_user/templates/auth_user/carts_view.html
{% extends 'base.html' %}

{% block title %}Carts view{% endblock title %}

{% block header %}Carts {{ user }} view{% endblock header %}   
    
{% block body %}   
   
    {% if carts %}

        <b>Your Carts :</b><br><br>

        {% for cart in carts %}
        <form action="{% url 'auth:cart-view' cart.session_id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Cart {{ cart.pk }}. Status - {{ cart.status }}" class="btn btn-primary btn-sm">
            <input type="hidden" name="session" value="{{ cart.session_id }}">
        </form>        
        <br>    
        {% endfor %}
    {% else%}
    <h4>There is no such information yet</h4>
    {% endif %}
    
    <br><br><br>
    {% comment %} <a href="{% url 'dirs:author-view-all' %}"><button type="button" class="btn btn-primary">All Authors</button></a> {% endcomment %}
    
{% endblock body %}

django_test/src/auth_user/templates/auth_user/login.html
{% extends 'login_base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}

{% block header %}Login{% endblock header %} 
  
{% block body %}   

<body class="text-center">
   
    <main class="form-signin">
        <form method="post">
            {% csrf_token %}
            <a class="mb-4" href="{% url 'dirs:home-page' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'icons/stock-logo.jpg' %}" width="108" height="157">
            </a>
            <h1 class="h3 mb-3 fw-normal">
                {% if form.errors %}
                    <p>Your username or password didn't match. Please try again.</p>
                {% elif next %}
                    {% if user.is_authenticated %}
                        <p>Your account doesn't have access to this page. To proceed,
                        please login with an account that has access.</p>
                    {% else %}
                        <p>Only registered users can see and use our promotions.</p>
                    {% endif %}          
                {% else %}
                    <p>Please sign in</p>
                {% endif %}
                
            </h1>
            <div class="form-floating">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="name@example.com" >
                <label for="floatingInput">Login/Email address</label>
            </div>
            <div class="form-floating">
                <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password" >
                <label for="floatingPassword">Password</label>
            </div>
        
            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            
                <button type="submit" value="submit" class="w-100 btn btn-lg btn-primary" > 
                    Sign in 
                </button>
                <br><br>
                <a href="{% url 'auth:registration' %}">
                    <button type="button" value="register" class="w-100 btn btn-lg btn-primary" > 
                        Registration 
                </button></a>

            {% if next %}
                <input type="hidden" name="next" value="{{ next }}">
            {% else %}
                <input type="hidden" name="next" value="{{ next }}">
            {% endif %}
        </form>     
    </main>
</body>

{% endblock body %}  

django_test/src/auth_user/templates/auth_user/registration.html
{% extends 'login_base.html' %}
{% load static %}
{% block title %}Registration{% endblock title %}

{% block header %}Registration{% endblock header %} 
  
{% block body %}   
<body class="text-center">
   
    <main class="form-signin">
        <form method="post">
            {% csrf_token %}
            <a class="mb-4" href="{% url 'dirs:home-page' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <img src="{% static 'icons/stock-logo.jpg' %}" width="108" height="157">
            </a>
            <h1 class="h3 mb-3 fw-normal">
                
            </h1>
            <div class="form-floating">
                <input type="text" name="username" class="form-control" id="floatingInput" placeholder="Username" >
                <label for="floatingInput">Username</label>
            </div>
            <div class="form-floating">
                <input type="password" name="email" class="form-control" id="floatingPassword" placeholder="name@example.com" >
                <label for="floatingPassword">Email</label>
            </div>
            <div class="form-floating">
                <input type="text" name="first_name" class="form-control" id="floatingInput" placeholder="Alexandr" >
                <label for="floatingInput">First Name</label>
            </div>
            <div class="form-floating">
                <input type="text" name="last_name" class="form-control" id="floatingInput" placeholder="Bobrikov" >
                <label for="floatingInput">Last Name</label>
            </div>
            <div class="form-floating">
                <input type="password" name="password1" class="form-control" id="floatingPassword" placeholder="Password" >
                <label for="floatingPassword">Password</label>
            </div>
            <div class="form-floating">
                <input type="password" name="password2" class="form-control" id="floatingPassword" placeholder="Password" >
                <label for="floatingPassword">Password Confirmation</label>
            </div>
        
            <div class="checkbox mb-3">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            {% if form.errors %}
                    <p>Something went wrong, please check the form.</p>
            {% endif %}
                <br><br>
                <a href="{% url 'auth:login' %}">
                    <button type="submit" name="Create User" value="register" class="w-100 btn btn-lg btn-primary" > 
                        Register
                    </button>
                </a> 
        </form> 
    </main>
</body>

{% endblock body %}  

django_test/src/auth_user/templates/auth_user/user_page.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User page{% endblock title %}

{% block header %}Hello {{user}}{% endblock header %} 
  
{% block body %}   

<a href="{% url 'auth:settings' %}" class="btn btn-primary"><input type="button" value="Account settings " class="btn btn-primary btn-sm"></a><br><br>

<a href="{% url 'auth:carts-view' %}" class="btn btn-primary"><input type="button" value="Your Carts " class="btn btn-primary btn-sm"></a><br>

{% endblock body %}  

django_test/src/auth_user/templates/auth_user/user_settings.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User page{% endblock title %}

{% block header %}Hello {{user}}{% endblock header %} 
  
{% block body %}   
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card profile-card">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		
		  		<form action="{% url 'auth:settings-update' %}" class="form-signin" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
			  		<h6 class="mt-4 field-heading">Email</h6>
                      {% if Email %}
                        <input type="email" name="email" class="form-control" value = "{{Email}}"
                        placeholder="{{Email}}" required autofocus value={{form.initial.email}}>
                      {% else %}
                        <input type="email" name="email" class="form-control" placeholder="Pls, fill this form for the first time">
                      {% endif %}
			  		
			  		
                    <h6 class="mt-4 field-heading">Username</h6>
                    {% if User_name %}
			  		<input type="text" name="username" class="form-control" value = "{{User_name}}"
                      placeholder="{{User_name}}" required value="{{form.initial.username}}">
                    {% else %}
                    <input type="text" name="username" class="form-control" placeholder="Pls, fill this form for the first time">
                    {% endif %}


                    <h6 class="mt-4 field-heading">First Name</h6>
                    {% if First_name %}
                    <input type="text" name="first_name" class="form-control" value = "{{First_name}}"
                      placeholder="{{First_name}}" required value="{{form.initial.first_name}}">
                    {% else %}
                    <input type="text" name="first_name" class="form-control" placeholder="Pls, fill this form for the first time">
                    {% endif %}
			  		

                    <h6 class="mt-4 field-heading">Last Name</h6>
                    {% if Last_name %}
                    <input type="text" name="last_name" class="form-control" value = "{{Last_name}}"
                      placeholder="Last_name" required value="{{form.initial.last_name}}">
                    {% else %}
                    <input type="text" name="last_name" class="form-control" placeholder="Pls, fill this form for the first time">
                    {% endif %}
			  		

					{% for field in form %}
					<p>
					{% for error in field.errors %}
					<p style="color: red">{{ error }}</p>
					{% endfor %}
					</p>
					{% endfor %}
					{% if form.non_field_errors %}
					<div style="color: red">
					<p>{{form.non_field_errors}}</p>
					</div>
					{% endif %}

					<div class="d-flex flex-column mt-4">
						<button class="mt-4 btn btn-primary flex-grow-1" type="submit">Save</button>
					</div>
					
				</form>
		  	</div>
		  </div>
		</div>
	</div>
</div>


{% endblock body %}  

django_test/src/auth_user/templates/auth_user/user_settings_update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}User page{% endblock title %}

{% block header %}Check your informations{% endblock header %} 
  
{% block body %}   
<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card profile-card">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		
		  		<form action="{% url 'auth:user-page' %}" class="form-signin" method="post" enctype="multipart/form-data">
                      {% csrf_token %}
			  		<h6 class="mt-4 field-heading">Email</h6>
                      {% if Email %}
                        <input type="email" name="email" class="form-control" value = "{{Email}}"
                        placeholder="{{Email}}" required autofocus value={{form.initial.email}}>
                      {% else %}
                        <input type="email" name="email" class="form-control" placeholder="Pls, fill this form for the first time">
                      {% endif %}
			  		
                    <h6 class="mt-4 field-heading">Username</h6>
                    {% if User_name %}
			  		<input type="text" name="username" class="form-control" value = "{{User_name}}"
                      placeholder="{{User_name}}" required value="{{form.initial.username}}">
                    {% else %}
                    <input type="text" name="username" class="form-control" placeholder="Pls, fill this form for the first time">
                    {% endif %}

                    <h6 class="mt-4 field-heading">First Name</h6>
                    {% if First_name %}
                    <input type="text" name="first_name" class="form-control" value = "{{First_name}}"
                      placeholder="{{First_name}}" required value="{{form.initial.first_name}}">
                    {% else %}
                    <input type="text" name="first_name" class="form-control" placeholder="Pls, fill this form for the first time">
                    {% endif %}
			  		
                    <h6 class="mt-4 field-heading">Last Name</h6>
                    {% if Last_name %}
                    <input type="text" name="last_name" class="form-control" value = "{{Last_name}}"
                      placeholder="Last_name" required value="{{form.initial.last_name}}">
                    {% else %}
                    <input type="text" name="last_name" class="form-control" placeholder="Pls, fill this form for the first time">
                    {% endif %}
			  		
					{% for field in form %}
					<p>
					{% for error in field.errors %}
					<p style="color: red">{{ error }}</p>
					{% endfor %}
					</p>
					{% endfor %}
					{% if form.non_field_errors %}
					<div style="color: red">
					<p>{{form.non_field_errors}}</p>
					</div>
					{% endif %}

					<div class="d-flex flex-column mt-4">
						<button class="mt-4 btn btn-primary flex-grow-1" type="submit">Save and go to your home page</button>
					</div>
					
				</form>
		  	</div>
		  </div>
		</div>
	</div>
</div>


{% endblock body %}  