django_test/src/auth_user/urls.py
from django.urls import path
from . import views

app_name = 'auth'

urlpatterns = [ 
    path('login', views.LoginUserView.as_view(), name = "login"),
    path('logout', views.LogoutUserView.as_view(), name = "logout"),
    path('registration', views.register_page, name = "registration"),
    path('user-page', views.UserPage.as_view(), name = "user-page"),
    path('settings', views.UserSettings.as_view(), name = "settings"),
    path('settings-update', views.UserSettingsUpdate.as_view(), name = "settings-update"),
    path('carts-view/', views.CartsList.as_view(), name = "carts-view"),
    path('cart_view/<int:pk>/', views.CartView.as_view(), name = "cart-view"),
    path('cart_view_update/<int:pk>/', views.UpdateCartView.as_view(), name = "cart-view-update"),

]

django_test/src/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [ 
    path('books_view/', views.BooksList.as_view(), name = "book-view-all"),
    path('book_view/<int:pk>/', views.BookView.as_view(), name = "book-view"),
    path('book_add/', views.BookAdd.as_view(), name = "book-add"),
    path('book_delete/<int:pk>/', views.BookDelete.as_view(), name = "book-delete"),
    path('book_edit/<int:pk>/', views.BookEdit.as_view(), name = "book-edit"),

]

django_test/src/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [ 
    path('add-to-cart', views.AddToCart.as_view(), name = "add-to-cart"),
    path('books_list', views.BooksInCartList.as_view(), name = "books_list"),
    path('delete_from_cart/<int:pk>', views.DeleteFromCart.as_view(), name = "delete_from_cart"),
    path('update-carts', views.OrderUpdateView.as_view(), name = "update-carts"),
    path('order-confirm', views.OrderConfirm.as_view(), name = "order-confirm"),
    path('order-status', views.OrderStatus.as_view(), name = "order-status"),
    path('order-status-update', views.ChangeStatus.as_view(), name = "order-status-update"),


]

django_test/src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from directory import views as dir
from django.conf import settings
from django.conf.urls.static import static
from . import local_vars 

urlpatterns = [ 
    path('', dir.Homepage.as_view(), name = "home-page"),
    path('admin/', admin.site.urls, name = "admin"),

    path("dirs/", include('directory.urls', namespace='dirs')),
    path("books/", include('books.urls', namespace='books')),
    path("sales/", include('sales.urls', namespace='sales')),
    path("auth/", include('auth_user.urls', namespace='auth_user')),
    path("orders/", include('orders.urls', namespace='orders')),
    path("managers/", include('manager_page.urls', namespace='managers')),
    
] 

if local_vars.SERVER == 'local':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_test/src/sales/urls.py
from django.urls import path
from . import views

app_name = 'sales'


urlpatterns = [ 
    
    # path('sales_view/', views.SalesCards.as_view(), name = "sales-view"),
    path('sales_book_add/', views.SalesBookAdd.as_view(), name = "sales-book-add"),
    path('sales_author_add/', views.SalesAuthorAdd.as_view(), name = "sales-author-add"),
    
    path('sales_books_view/', views.SalesBooksView.as_view(), name = "sales-books-view"),
    path('sales_authors_view/', views.SalesAuthorsView.as_view(), name = "sales-authors-view"),

    path('sales_book_view/<int:pk>/', views.SalesBookView.as_view(), name = "sales-book-view"),
    path('sales_author_view/<int:pk>/', views.SalesAuthorView.as_view(), name = "sales-author-view"),

    path('sales_book_edit/<int:pk>/', views.SalesBookEdit.as_view(), name = "sales-book-edit"),
    path('sales_book_delete/<int:pk>/', views.SalesBookDelete.as_view(), name = "sales-book-delete"),

    path('sales_author_edit/<int:pk>/', views.SalesAuthorEdit.as_view(), name = "sales-author-edit"),
    path('sales_author_delete/<int:pk>/', views.SalesAuthorDelete.as_view(), name = "sales-author-delete"),
]

django_test/src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'bs/css/bootstrap.min.css' %}" rel="stylesheet" >
    <script src="{% static 'bs/js/bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="icon" href="{% static 'icons/stock-logo_1.jpg' %}">

    <script src="{% static 'css_template/footer.css' %}"></script>
    <script src="{% static 'css_template/navbar.css' %}"></script>
    <title>{% block title %}Pls add any title{% endblock title %}</title>
</head>
<style>
    body { 
        margin-left: 5px;
        margin-right: 5px;
        margin-top: 2px;
    }

    table {
        width: 250px; 
        margin: auto; 
       }
       td {
        text-align: center; 
       }
</style>

<body>

    {% include 'navbar.html' %}

    <h1>{% block header %}Pls add any header{% endblock header %}</h1>
    {% include 'horizontal-line.html' %}
    {% block body %}{% endblock body %}
    <br>
    {% include 'horizontal-line.html' %}
    {% block footer %}{% include 'footer.html' %}{% endblock footer %}

    
</body>
</html>

django_test/src/templates/base_manager.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'bs/css/bootstrap.min.css' %}" rel="stylesheet" >
    <script src="{% static 'bs/js/bootstrap.bundle.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="icon" href="{% static 'icons/stock-logo_1.jpg' %}">

    <script src="{% static 'css_template/footer.css' %}"></script>
    <script src="{% static 'css_template/navbar.css' %}"></script>
    <title>{% block title %}Pls add any title{% endblock title %}</title>
</head>
<style>
    body { 
        margin-left: 5px;
        margin-right: 5px;
        margin-top: 2px;
    }

    table {
        width: 250px; 
        margin: auto; 
       }
       td {
        text-align: center; 
       }
</style>

<body>

    {% include 'navbar.html' %}

    <h1>{% block header %}Pls add any header{% endblock header %}</h1>
    {% include 'horizontal-line.html' %}

    {% block body %}  {% endblock body %}
    <br>

    
</body>
</html>

django_test/src/templates/footer.html
    <footer class="py-5">
      <div class="row">
        <div class="col-6 col-md-2 mb-3">
          <h5>Your choice</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="{% url 'dirs:home-page' %}" class="nav-link p-0 text-muted">Home</a></li>
            <li class="nav-item mb-2"><a href="{% url 'books:book-view-all' %}" class="nav-link p-0 text-muted">All Books</a></li>
            <li class="nav-item mb-2"><a href="{% url 'dirs:publishing-view-all' %}" class="nav-link p-0 text-muted">All Publishings house</a></li>
            <li class="nav-item mb-2"><a href="{% url 'dirs:genres-view-all' %}" class="nav-link p-0 text-muted">All Genres</a></li>
            <li class="nav-item mb-2"><a href="{% url 'dirs:author-view-all' %}" class="nav-link p-0 text-muted">All Authors</a></li>
            <li class="nav-item mb-2"><a href="{% url 'dirs:series-view-all' %}" class="nav-link p-0 text-muted">All Series</a></li>
          </ul>
        </div>
  
        <div class="col-6 col-md-2 mb-3">
          <h5>Sales</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="{% url 'sales:sales-books-view' %}" class="nav-link p-0 text-muted">Books</a></li>
            <li class="nav-item mb-2"><a href="{% url 'sales:sales-authors-view' %}" class="nav-link p-0 text-muted">Authors</a></li>
          </ul>
        </div>
  
        <div class="col-6 col-md-2 mb-3">
          <h5>Section</h5>
          <ul class="nav flex-column">
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Home</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
          </ul>
        </div>
  
        <div class="col-md-5 offset-md-1 mb-3">
          <form>
            <h5>Subscribe to our newsletter</h5>
            <p>Monthly digest of what's new and exciting from us.</p>
            <div class="d-flex flex-column flex-sm-row w-100 gap-2">
              <label for="newsletter1" class="visually-hidden">Email address</label>
              <input id="newsletter1" type="text" class="form-control" placeholder="Email address">
              <button class="btn btn-primary" type="button">Subscribe</button>
            </div>
          </form>
        </div>
      </div>

django_test/src/templates/horizontal-line.html
<hr>

django_test/src/templates/login_base.html
<!doctype html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Signin{% endblock title %}</title>

        <!-- Bootstrap core CSS -->
        <link href="{% static 'bs/css/bootstrap.min.css' %}" rel="stylesheet" >
        <!-- Favicons -->
        <link rel="icon" href="{% static 'icons/stock-logo_1.jpg' %}">
        
        <meta name="theme-color" content="#7952b3">

        <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
            font-size: 3.5rem;
            }
        }
        </style>

        
        <!-- Custom styles for this template -->
        <link href="{% static 'login/signin.css' %}" rel="stylesheet">
    </head>
    {% block body %}
    
    {% endblock body %}
  
</html>

django_test/src/templates/navbar.html
{% load static %}
<header class="p-3 text-bg-dark">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
        <a href="{% url 'dirs:home-page' %}" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
          <img src="{% static 'icons/stock-logo.jpg' %}" width="100" height="111">
        </a>

        <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
          <li><a href="{% url 'books:book-view-all' %}" class="nav-link px-2 text-white">Books</a></li>
          <li><a href="{% url 'dirs:publishing-view-all' %}" class="nav-link px-2 text-white">Publishings house</a></li>
          <li><a href="{% url 'dirs:genres-view-all' %}" class="nav-link px-2 text-white">Genres</a></li>
          <li><a href="{% url 'dirs:author-view-all' %}" class="nav-link px-2 text-white">Authors</a></li>
          <li><a href="{% url 'dirs:series-view-all' %}" class="nav-link px-2 text-white">Series</a></li>
          <li><a href="{% url 'sales:sales-books-view' %}" class="nav-link px-2 text-white">Books Sales</a></li>
          <li><a href="{% url 'sales:sales-authors-view' %}" class="nav-link px-2 text-white">Authors Sales</a></li>
        </ul>

        <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" role="search">
          <input type="search" class="form-control form-control-dark text-bg-dark" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          
          {% if user.is_authenticated %}
            {% if session %}   
            <a href="{% url 'orders:books_list' %}"><button type="button" class="btn btn-outline-light me-2"><i class="bi bi-cart-check"></i></a></button>
            {% endif %}
          <button type="button" class="btn btn-light"><a href="{% url 'auth:user-page' %}"> {{ user }} </a></button>
          <button type="button" class="btn btn-light"><a href="{% url 'auth:logout' %}">Logout</a></button>
          {% else %}
          <button type="button" class="btn btn btn-light"><a href="{% url 'auth:login' %}"> Login </a></button>
          {% endif %}

          {% for group in request.user.groups.all %}
            {% if group.name == 'Admin' or group.name == 'Super_managers' or group.name == 'Managers'%}
              <button type="button" class="btn btn-light"><a href="{% url 'managers:main-menu' %}">Manager menu</a></button>
            {% endif %}
          {% endfor %}

        </div>
      </div>
    </div>
  </header>