django_test/src/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [ 
    path('books_view/', views.BooksList.as_view(), name = "book-view-all"),
    path('book_view/<int:pk>/', views.BookView.as_view(), name = "book-view"),
    path('book_add/', views.BookAdd.as_view(), name = "book-add"),
    path('book_delete/<int:pk>/', views.BookDelete.as_view(), name = "book-delete"),
    path('book_edit/<int:pk>/', views.BookEdit.as_view(), name = "book-edit"),

]

django_test/src/directory/urls.py
from django.urls import path
from . import views

app_name = 'dirs'

urlpatterns = [ 
    path('', views.Homepage.as_view(), name = "home-page"),

    # path('books_view/', views.BooksList.as_view(), name = "book-view-all"),
    # path('book_view/<int:pk>/', views.BookView.as_view(), name = "book-view"),
    # path('book_add/', views.BookAdd.as_view(), name = "book-add"),
    # path('book_delete/<int:pk>/', views.BookDelete.as_view(), name = "book-delete"),
    # path('book_edit/<int:pk>/', views.BookEdit.as_view(), name = "book-edit"),
    
    path('authors_view/', views.AuthorsList.as_view(), name = "author-view-all"),
    path('author_view/<int:pk>/', views.AuthorView.as_view(), name = "author-view"),
    path('author_edit/<int:pk>/', views.AuthorEdit.as_view(), name = "author-edit"),
    path('author_delete/<int:pk>/', views.AuthorDelete.as_view(), name = "author-delete"),
    path('author_add/', views.AuthorAdd.as_view(), name = "author-add"),

    path('publishings_view/', views.PublishingsList.as_view(), name = "publishing-view-all"),
    path('publishing_view/<int:pk>/', views.PublishingView.as_view(), name = "publishing-view"),
    path('publishing_edit/<int:pk>/', views.PublishingEdit.as_view(), name = "publishing-edit"),
    path('publishing_delete/<int:pk>/', views.PublishingDelete.as_view(), name = "publishing-delete"),
    path('publishing_add/', views.PublishingAdd.as_view(), name = "publishing-add"),

    path('serieses_view/', views.SeriesList.as_view(), name = "series-view-all"),
    path('series_view/<int:pk>/', views.SeriesView.as_view(), name = "series-view"),
    path('series_edit/<int:pk>/', views.SeriesEdit.as_view(), name = "series-edit"),
    path('series_delete/<int:pk>/', views.SeriesDelete.as_view(), name = "series-delete"),
    path('series_add/', views.SeriesAdd.as_view(), name = "series-add"),

    path('genres_view/', views.GenresList.as_view(), name = "genres-view-all"),
    path('genre_view/<int:pk>/', views.GenreView.as_view(), name = "genre-view"),
    path('genre_edit/<int:pk>/', views.GenreEdit.as_view(), name = "genre-edit"),
    path('genre_delete/<int:pk>/', views.GenreDelete.as_view(), name = "genre-delete"),
    path('genre_add/', views.GenreAdd.as_view(), name = "genre-add"),

]

django_test/src/proj/urls.py
from django.contrib import admin
from django.urls import path, include
from directory import views as dir
from django.conf import settings
from django.conf.urls.static import static
from . import local_vars 

urlpatterns = [ 
    path('', dir.Homepage.as_view(), name = "home-page"),
    path('admin/', admin.site.urls, name = "admin"),

    path("dirs/", include('directory.urls', namespace='dirs')),
    path("books/", include('books.urls', namespace='books')),
    path("sales/", include('sales.urls', namespace='sales')),
    path("auth/", include('auth_user.urls', namespace='auth_user')),
    path("orders/", include('orders.urls', namespace='orders')),
    path("managers/", include('manager_page.urls', namespace='managers')),
    
] 

if local_vars.SERVER == 'local':
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_test/src/directory/models.py
from django.db import models

# Create your models here.

class Genre(models.Model):
    name = models.CharField(
        verbose_name='Genre name',
        max_length=20,
    )
    description= models.TextField(
        verbose_name='Genre description',
        blank =  True,
        null = True
    )

    def __str__(self) -> str:
        return str(self.id) + '. ' + self.name


class Series(models.Model):
    name = models.CharField(
        verbose_name='Series',
        max_length=30,
    )
    description= models.TextField(
        verbose_name='Series description',
        blank =  True,
        null = True
    )

    def __str__(self) -> str:
        return str(self.pk) + '. ' + self.name

class Publishing_house(models.Model):
    name = models.CharField(
        verbose_name='Publishing house',
        max_length=30,
    )
    description= models.TextField(
        verbose_name='Publishing house description',
        blank =  True,
        null = True
    )

    def __str__(self) -> str:
        return str(self.pk) + '. ' + self.name

class Author(models.Model):
    name = models.CharField(
        verbose_name='Author',
        max_length=30,
    )
    description= models.TextField(
        verbose_name='Author description',
        blank =  True,
        null = True
    )

    def __str__(self) -> str:
        return str(self.pk) + '. ' + self.name

django_test/src/directory/forms.py
from django import forms
from . import models

# class AddBookForm(forms.ModelForm):
#     class Meta:
#         model = models.Book
#         fields = '__all__'
    
class AddAuthorForm(forms.ModelForm):
    class Meta:
        model = models.Author
        fields = '__all__'

class AddPublishingForm(forms.ModelForm):
    class Meta:
        model = models.Publishing_house
        fields = '__all__'

class AddGenreForm(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = '__all__'

class AddSeriesForm(forms.ModelForm):
    class Meta:
        model = models.Series
        fields = '__all__'

class AddGenresForm(forms.ModelForm):
    class Meta:
        model = models.Genre
        fields = '__all__'

django_test/src/directory/views.py
from directory import models
from . import forms
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import PermissionRequiredMixin
from books import models as book_models

# Create your views here.
    
class Homepage(generic.TemplateView):
    template_name = "directory/home_page.html"
    
    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        print(self.request.user)
        books = book_models.Book.objects.all()
        context['books'] = books      
        return context  
        
    def post(self, request, *args, **kwargs):
        context = self.get_context_data(*args, **kwargs)
        return self.render_to_response(context)

# Authors
class AuthorView(generic.DetailView):
    template_name = "directory/author_view.html"
    model = models.Author

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        books = book_models.Book.objects.filter(author=self.object.pk)
        context['books'] = books      
        return context
    
class AuthorsList(generic.ListView):
    template_name = "directory/authors_view.html"
    model = models.Author

class AuthorEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "directory/author_edit.html"
    model = models.Author
    form_class = forms.AddAuthorForm
    login_url = '/auth/login'
    permission_required = 'directory.change_author'

    def get_success_url(self):
        return reverse_lazy("dirs:author-view", kwargs = {'pk' : self.object.pk})

class AuthorDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "directory/author_delete.html"
    model = models.Author
    success_url = "/dirs/authors_view/"
    permission_required = 'directory.delete_author'

class AuthorAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "directory/author_add.html"
    model = models.Author
    form_class = forms.AddAuthorForm
    permission_required = 'directory.add_author'

    def get_success_url(self):
        return reverse_lazy("dirs:author-view", kwargs = {'pk' : self.object.pk})

# Publishings
class PublishingsList(generic.ListView):
    template_name = "directory/publishings_view.html"
    model = models.Publishing_house

class PublishingView(generic.DetailView):
    template_name = "directory/publishing_view.html"
    model = models.Publishing_house

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        books = book_models.Book.objects.filter(publishing=self.object.pk)
        context['books'] = books        
        return context

class PublishingAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "directory/publishing_add.html"
    model = models.Publishing_house
    form_class = forms.AddPublishingForm
    permission_required = 'directory.add_publishing_house'

    def get_success_url(self):
        return reverse_lazy("dirs:publishing-view", kwargs = {'pk' : self.object.pk})

class PublishingEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "directory/publishing_edit.html"
    model = models.Publishing_house
    form_class = forms.AddPublishingForm
    permission_required = 'directory.change_publishing_house'

    def get_success_url(self):
        return reverse_lazy("dirs:publishing-view", kwargs = {'pk' : self.object.pk})

class PublishingDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "directory/publishing_delete.html"
    model = models.Publishing_house
    success_url = "/dirs/publishings_view/"
    permission_required = 'directory.delete_publishing_house'

# Series
class SeriesList(generic.ListView):
    template_name = "directory/serieses_view.html"
    model = models.Series

class SeriesView(generic.DetailView):
    template_name = "directory/series_view.html"
    model = models.Series
    
    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        books = book_models.Book.objects.filter(series=self.object.name)
        context['books'] = books      
        return context

class SeriesAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "directory/series_add.html"
    model = models.Series
    form_class = forms.AddSeriesForm
    permission_required = 'directory.add_series'

    def get_success_url(self):
        return reverse_lazy("dirs:series-view", kwargs = {'pk' : self.object.pk})

class SeriesEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "directory/series_edit.html"
    model = models.Series
    form_class = forms.AddSeriesForm
    permission_required = 'directory.change_series'

    def get_success_url(self):
        return reverse_lazy("dirs:series-view", kwargs = {'pk' : self.object.pk})

class SeriesDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "directory/series_delete.html"
    model = models.Series
    success_url = "/dirs/serieses_view/"
    permission_required = 'directory.delete_series'

# 
# Genres
class GenresList(generic.ListView):
    template_name = "directory/genres_view.html"
    model = models.Genre

class GenreView(generic.DetailView):
    template_name = "directory/genre_view.html"
    model = models.Genre

    def get_context_data(self,*args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        books = book_models.Book.objects.filter(genre=self.object.pk)
        context['books'] = books      
        return context


class GenreAdd(PermissionRequiredMixin, generic.CreateView):
    template_name = "directory/genre_add.html"
    model = models.Genre
    form_class = forms.AddGenreForm
    permission_required = 'directory.add_genre'

    def get_success_url(self):
        return reverse_lazy("dirs:genre-view", kwargs = {'pk' : self.object.pk})

class GenreEdit(PermissionRequiredMixin, generic.UpdateView):
    template_name = "directory/genre_edit.html"
    model = models.Genre
    form_class = forms.AddGenreForm
    permission_required = 'directory.change_genre'

    def get_success_url(self):
        return reverse_lazy("dirs:genre-view", kwargs = {'pk' : self.object.pk})

class GenreDelete(PermissionRequiredMixin, generic.DeleteView):
    template_name = "directory/genre_delete.html"
    model = models.Genre
    success_url = "/dirs/genres_view/"
    permission_required = 'directory.delete_genre'

django_test/src/directory/templates/directory/author_add.html
{% extends 'base.html' %}

{% block title %}Author add{% endblock title %}

{% block header %}Author add{% endblock header %}   
    
{% block body %}   
    <ul>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </ul>

{% endblock body %}

django_test/src/directory/templates/directory/author_view.html
{% extends 'base.html' %}

{% block title %}Author view{% endblock title %}

{% block header %}Author {{ object.name }} view{% endblock header %}   
    
{% block body %}   
   
    <b>Description:</b> {{ object.description }}<br><br><br>
    {% if books %}
        <b>Books this authors :</b><br><br>
        {% for book in books %}
            <a href="{% url 'books:book-view' book.pk %}">{{ book.name }}</a><br>
        {% endfor %}
    {% else%}
    <h4>There is no such information yet</h4>
    {% endif %}
    
    <br><br><br>
    <a href="{% url 'dirs:author-view-all' %}"><button type="button" class="btn btn-primary">All Authors</button></a>
    
{% endblock body %}

django_test/src/directory/templates/directory/authors_view.html
{% extends 'base.html' %}

{% block title %}Author view{% endblock title %}

{% block header %}Author view{% endblock header %}   
    
{% block body %}   
    <ul>
        {% for author in object_list %}
        <li>
            <a href="{% url 'dirs:author-view' author.pk %}">{{ author.name }}</a>
            {% for group in request.user.groups.all %}
                {% if group.name == 'Admin' or group.name == 'Super_managers' %}
                    <a href="{% url 'dirs:author-edit' author.pk %}"><i class="bi bi-pencil"></i></a>
                    <a href="{% url 'dirs:author-delete' author.pk %}"><i class="bi bi-trash"></i></a>
                {% elif group.name == 'Managers'%}
                    <a href="{% url 'dirs:author-edit' author.pk %}"><i class="bi bi-pencil"></i></a>
                {% endif %}
            {% endfor %}

        </li>
        {% endfor %}
    </ul>
    {% for group in request.user.groups.all %}
        {% if group.name == 'Admin' or group.name == 'Super_managers' or group.name == 'Managers' %}
            <a href="{% url 'dirs:author-add' %}"><button type="button" class="btn btn-primary">Add Author</button></a>
        {% endif %}
    {% endfor %}
    <br><br><br>

{% endblock body %}

django_test/src/directory/templates/directory/book_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Books add{% endblock title %}

{% block header %}Books add{% endblock header %}

{% block body %}
    <ul>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-primary">
        </form>
    </ul>

{% endblock body %}

django_test/src/directory/templates/directory/book_edit.html
{% extends 'base.html' %}

{% block title %}Books edit{% endblock title %}

{% block header %}Books edit{% endblock header %}

{% block body %}
    <ul>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </ul>

{% endblock body %}

django_test/src/directory/templates/directory/genre_edit.html
{% extends 'base.html' %}

{% block title %}Genre edit{% endblock title %}

{% block header %}Genre edit{% endblock header %}

{% block body %}
    <ul>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </ul>

{% endblock body %}

django_test/src/directory/templates/directory/genres_view.html
{% extends 'base.html' %}

{% block title %}Genre view{% endblock title %}

{% block header %}Genre view{% endblock header %}

{% block body %}
    <ul>
        {% for genre in object_list %}
        <li>
            <a href="{% url 'dirs:genre-view' genre.pk %}">{{ genre.name }}</a>
            {% for group in request.user.groups.all %}
                {% if group.name == 'Admin' or group.name == 'Super_managers' %}
                    <a href="{% url 'dirs:genre-edit' genre.pk %}"><i class="bi bi-pencil"></i></a>
                    <a href="{% url 'dirs:genre-delete' genre.pk %}"><i class="bi bi-trash"></i></a>
                {% elif group.name == 'Managers'%}
                    <a href="{% url 'dirs:genre-edit' genre.pk %}"><i class="bi bi-pencil"></i></a>
                {% endif %}
            {% endfor %}
        </li>
        {% endfor %}
    </ul>
    {% for group in request.user.groups.all %}
        {% if group.name == 'Admin' or group.name == 'Super_managers' or group.name == 'Managers' %}
            <a href="{% url 'dirs:genre-add' %}"><button type="button" class="btn btn-primary">Add genre</button></a>
        {% endif %}
    {% endfor %}
    <br><br><br>

{% endblock body %}

django_test/src/directory/templates/directory/publishing_add.html
{% extends 'base.html' %}

{% block title %}Publishings add{% endblock title %}

{% block header %}Publishings add{% endblock header %}

{% block body %}
    <ul>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </ul>

{% endblock body %}

django_test/src/directory/templates/directory/publishing_delete.html
{% extends 'base.html' %}

{% block title %}Publishings view{% endblock title %}

{% block header %}Publishings delete. Are you sure to delete {{ object.name }} ??{% endblock header %}

{% block body %}
    <ul>
        <form action="" method="post">
            {% csrf_token %}
            <br>
            <input type="submit">
        </form>
    </ul>

{% endblock body %}

django_test/src/directory/templates/directory/publishing_view.html
{% extends 'base.html' %}

{% block title %}Publishings view{% endblock title %}

{% block header %}Publishing {{ object.name }} view{% endblock header %}

{% block body %}

    <b>Description:</b> {{ object.description }}
    <br><br><br>
    {% if books %}
        <b>Books they published :</b><br><br>
        {% for book in books %}
            <a href="{% url 'books:book-view' book.pk %}">{{ book.name }}</a><br>
        {% endfor %}
    {% else%}
        <h4>There is no such information yet</h4>
    {% endif %}
    <br><br><br>
    <a href="{% url 'dirs:publishing-view-all' %}"><button type="button" class="btn btn-primary">All Publishings Houses</button></a>
{% endblock body %}

django_test/src/directory/templates/directory/series_add.html
{% extends 'base.html' %}

{% block title %}Series add{% endblock title %}

{% block header %}Series add{% endblock header %}

{% block body %}
    <ul>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </ul>

{% endblock body %}

django_test/src/directory/templates/directory/series_edit.html
{% extends 'base.html' %}

{% block title %}Series edit{% endblock title %}

{% block header %}Series edit{% endblock header %}

{% block body %}
    <ul>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit">
        </form>
    </ul>

{% endblock body %}

django_test/src/directory/templates/directory/series_view.html
{% extends 'base.html' %}

{% block title %}Series view{% endblock title %}

{% block header %}Series {{ object.name }} view{% endblock header %}

{% block body %}
    
    <b>Description:</b> {{ object.description }}<br><br><br>
    {% if books %}
        <b>Books this series :</b><br><br>
        {% for book in books %}
            <a href="{% url 'books:book-view' book.pk %}">{{ book.name }}</a><br>
        {% endfor %}
    {% else%}
    <h4>There is no such information yet</h4>
    {% endif %}
    <br><br><br>
    <a href="{% url 'dirs:series-view-all' %}"><button type="button" class="btn btn-primary">All series</button></a>

{% endblock body %}

django_test/src/directory/templates/directory/serieses_view.html
{% extends 'base.html' %}

{% block title %}Series view{% endblock title %}

{% block header %}Series view{% endblock header %}

{% block body %}
    <ul>
        {% for series in object_list %}
        <li>
            <a href="{% url 'dirs:series-view' series.pk %}">{{ series.name }}</a>
            {% for group in request.user.groups.all %}
                {% if group.name == 'Admin' or group.name == 'Super_managers' %}
                    <a href="{% url 'dirs:series-edit' series.pk %}"><i class="bi bi-pencil"></i></a>
                    <a href="{% url 'dirs:series-delete' series.pk %}"><i class="bi bi-trash"></i></a>
                {% elif group.name == 'Managers'%}
                    <a href="{% url 'dirs:series-edit' series.pk %}"><i class="bi bi-pencil"></i></a>
                {% endif %}
            {% endfor %}
        </li>
        {% endfor %}
    </ul>
    {% for group in request.user.groups.all %}
        {% if group.name == 'Admin' or group.name == 'Super_managers' or group.name == 'Managers' %}
            <a href="{% url 'dirs:series-add' %}"><button type="button" class="btn btn-primary">Add series</button></a>
        {% endif %}
    {% endfor %}
    <br><br><br>  
    
{% endblock body %}